/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleJenkins;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    
    public void employeeTest() {
    	Employee emp = new FullTimeEmployee();
    	assertEquals("Full Time Employee", emp.getEmployeeType()) ;
       	Employee emp1 = new PartTimeEmployee();
       	assertEquals("Part time Employee", emp1.getEmployeeType()); 
    }
}
